# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paradoxNewUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 824)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main = QtWidgets.QLabel(self.centralwidget)
        self.main.setGeometry(QtCore.QRect(0, 0, 1131, 821))
        self.main.setStyleSheet("background:cyan;\n"
"border: 2px solid white;")
        self.main.setText("")
        self.main.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/main.gif"))
        self.main.setScaledContents(True)
        self.main.setObjectName("main")
        self.inner_crc = QtWidgets.QLabel(self.centralwidget)
        self.inner_crc.setGeometry(QtCore.QRect(470, 340, 191, 141))
        self.inner_crc.setText("")
        self.inner_crc.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/circle.gif"))
        self.inner_crc.setScaledContents(True)
        self.inner_crc.setObjectName("inner_crc")
        self.paradox = QtWidgets.QLabel(self.centralwidget)
        self.paradox.setGeometry(QtCore.QRect(400, 630, 351, 91))
        self.paradox.setText("")
        self.paradox.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/title.jpg"))
        self.paradox.setScaledContents(True)
        self.paradox.setObjectName("paradox")
        self.initial = QtWidgets.QLabel(self.centralwidget)
        self.initial.setGeometry(QtCore.QRect(650, 10, 471, 211))
        self.initial.setText("")
        self.initial.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/initial.gif"))
        self.initial.setScaledContents(True)
        self.initial.setObjectName("initial")
        self.outer_crc = QtWidgets.QLabel(self.centralwidget)
        self.outer_crc.setGeometry(QtCore.QRect(20, 510, 341, 311))
        self.outer_crc.setText("")
        self.outer_crc.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/void.gif"))
        self.outer_crc.setScaledContents(True)
        self.outer_crc.setObjectName("outer_crc")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 421, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/panel.jpg"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 60, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(100)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius:none;\n"
"color: white;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 160, 231, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/alien.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.load = QtWidgets.QLabel(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(840, 530, 251, 251))
        self.load.setText("")
        self.load.setPixmap(QtGui.QPixmap("C:/Users/NAGENDRA/OneDrive/Desktop/paradoxuitools/4705530785b66c5fcbdc84fba4315dc4_w200.gif"))
        self.load.setScaledContents(True)
        self.load.setObjectName("load")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 740, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white;\n"
"background:rgb(0, 138, 0);\n"
"border-color:white;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 740, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: white;\n"
"background:rgb(255, 0, 0);\n"
"border-color:white;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
